### ISSUE TITLE
create_note_from_content not reading file in properly

### ISSUE THREAD

**Issue by bpruitt-goddard** [yasserglez/pyenscript#1]
I am trying to use `create_note_from_content` to write the contents of a string to a new note. However, when the temp file is read inside of ENScript.exe, it appears to be reading it as a raw file instead of parsing the bytes as text. I included a screenshot below of what the note looks like in Evernote.

I was able to fix this by updating the call to tempfile.NamedTemporaryFile to include a suffix parameter `suffix='.txt'` and that causes it to properly interpret the data. Is this the preferred way to do this?

![image](https://cloud.githubusercontent.com/assets/2429731/4692073/7db9afe2-5749-11e4-8fe1-baac8679bf1e.png)

**Comment by yasserglez** [comment]
Yes, I think that's the solution. I'll update the code. Thanks!
